### ISSUE TITLE
Q: Will this run on a H801?

### ISSUE THREAD

**Issue by Moonbase59** [penfold42/ESPixelBoard#17]
I got a few cheap ESP8266-based H801 RGB2W light controllers (https://www.aliexpress.com/item/rgbww-strip-WiFi-controller-1-port-control-200-lights-communicate-with-Android-phone-via-WLAN-to/32301423622.html) for my "dumb" RGB LED strips and was wondering if I could use these with _both_ MQTT and DMX (E1.31).

For some reason, PWM support seems to have been in forkineye’s ESPixelStick but is now gone.

Questions:

1. Would your code run on a H801 device?
2. Would you find the heart to merge forkineye’s latest master branch into yours (after the weekend, because I made a PR with some changes)?

N.B.: The H801 uses the following pin layout (Arduino numbering):

* red: 12
* green: 13
* blue: 15
* white 1: 14
* white 2: 4

* onboard LED D1: 5
* onboard LED D2: 1

* TX GPIO2
* RX GPIO3

**Comment by penfold42** [comment]
1. Yep ! The webUI even includes the h801 labels next to the gpios

2. Yep also - I’m planning to track as closely as I can. The effect updates didn’t merge cleanly so I have some to resolve some conflicts there before I update the mqtt changes from the last few days

**Comment by Moonbase59** [comment]
Hey, good news! So I reckon I give it a try as soon as you’ve merged in the newest stuff and I have some time to play with the H801s. :-)

**Comment by penfold42** [comment]
Be careful - don’t power it externally AND connect the FTDI serial at the same time.

**Comment by Moonbase59** [comment]
Hee hee, of course not ;-) I’ve been "ESPURNA’ing" _lots_ of 230V E27 LED bulbs and power switches lately. Thanks anyway :-)

**Comment by Moonbase59** [comment]
Well, I had some spare time to try it on a H801 today:
* Folder needs to be renamed to "ESPixelStick", conflicts with the real one (I renamed `ESPixelStick.ino` to `ESPixelBoard.ino`)
* I have
  ```
  /* Enable support for rotary encoder */
  //#define ESPS_ENABLE_BUTTONS
  ```
  but still get
  ```
  sketch/buttons.cpp:4:27: fatal error: RotaryEncoder.h: No such file or directory
   #include <RotaryEncoder.h>
  ```

**Comment by penfold42** [comment]
It _should_ be all good to go

It took a little while to add support for multiframe websocket frames - saving device settings was broken cos of that.

**Comment by penfold42** [comment]
Done

**Comment by Moonbase59** [comment]
I’ll give it a try one of these days. Good to see you’re still on it :-)
