### ISSUE TITLE
master is not compiling

### ISSUE THREAD

**Issue by priyankchouksey** [penfold42/ESPixelBoard#42]
The master branch is not compiling, raising error 'RotaryEncoder.h: No such file or directory' in button.cpp.
Are you missing the inclusion of this lib in documentation (readme.md).

Tried to add https://github.com/mathertel/RotaryEncoder but then getting other errors:

Arduino: 1.8.7 (Mac OS X), Board: "WeMos D1 R1, 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

In file included from /Users/priyank/myWorkSpace/ChristmasLights/penfold42/ESPixelStick/ESPixelStick.ino:45:0:
sketch/wshandler.h: In function 'void procX(uint8_t*, AsyncWebSocketClient*)':
wshandler.h:134:45: error: 'struct e131_stats_t' has no member named 'last_seen'
             e131J["last_seen"] = e131.stats.last_seen ? (String) (millis() - e131.stats.last_seen) : "never";
                                             ^
wshandler.h:134:89: error: 'struct e131_stats_t' has no member named 'last_seen'
             e131J["last_seen"] = e131.stats.last_seen ? (String) (millis() - e131.stats.last_seen) : "never";
                                                                                         ^
exit status 1
'struct e131_stats_t' has no member named 'last_seen'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by priyankchouksey** [comment]
Got it. The ESP Async E131 lib, I had my copy from forkintheeye. Including from penfold42 repository fixed the error.

**Comment by penfold42** [comment]
Thanks - ive updated my README
