### ISSUE TITLE
Disable Effect also starts with DataSource Web.

### ISSUE THREAD

**Issue by priyankchouksey** [penfold42/ESPixelBoard#44]
Select some Effect, Check Enable Startup effect, save, Select Effect = Disable save.

When restarted, the ESP starts with DataSource Web, it should be E131. The better option is to uncheck and disable "Enable startup effect' checkbox on Effect = 'Disable'

**Comment by penfold42** [comment]
Thanks for the report.

I’m not a fan of unexpected GUI consequences.

Maybe on boot just ignoring the startup effect option if the effect == disabled ?

**Comment by penfold42** [comment]
Fixed in https://github.com/penfold42/ESPixelBoard/commit/a55683b19d0c12a87614e0a501532885eaf4b80d
Also squashed a small bug with the webUI not reflecting enabled status 

Thanks !
